### ISSUE TITLE
analog stick vs d-pad

### ISSUE THREAD

**Issue by endquote** [aashreys/prototyper#2]
When setting up prototypes, it seems like the plugin sets up navigation to run from the analog stick.

It would be neat if you could choose analog stick, d-pad, or both. Of course for both you'd need a second prototype interaction defined.

**Comment by aashreys** [comment]
You should be able to choose D-Pad in the navigation section while generating or linking a prototype. 

To add on additional navigation methods, choose a different navigation method and use the Link feature on your existing prototype frames.

Lemme know if this resolves your issue.

**Comment by endquote** [comment]
Yes, sorry! I missed it. Cool that you can do the shoulder buttons too.
